### ISSUE TITLE
add CodeEditorPopupWindow to gui.components

### ISSUE THREAD

**Issue by nattanyz** [AY1920S1-CS2103-F09-2/main#136]
popup window for answering a JavaScript card during a Test.
upon saving (or closing the window -- tbd, let me know what you decide on), the code will be evaluated. return updates to score, @shawnpunchew11 how should this be done?

`CodeEditorPopupWindow` will be instantiated by `Gui.renderCodeEditorPopupWindow(JavaScriptCard card)`, to be implemented by @nattanyz . logic to be implemented in `Responder`? not sure, @PhireHandy ? 
might want to use `TextArea` or `WebView` for this, or external libraries e.g. https://github.com/FXMisc/RichTextFX. you may need multiple components for the window (feel free to add more files) e.g. the editor itself, "save" button etc.
also may need: attribute in JavaScript cards for storing prompt text/sample code snippets, which will already be in the code editor when the window pops up.

**Comment by huiminlim** [comment]
@nattanyz @timothyleong97 a shortcut implementation is to load the user's completed code from a file path and evaluate from the file. We can call @AHaliq storage load methods to achieve this. But it is still a design decision, so this is a suggestion if you are short of time/consider this time efficient.

**Comment by huiminlim** [comment]
Also, suggest @timothyleong97 @nattanyz to include in DG to highlight the difference between the Java(script) evaluator and a compiler with input-output redirection functionality. Perhaps can do by outlining the general vision with UI

i.e. encourage user with small steps to incrementally code, handling corner cases subsequently in a incremental coding pov.
Then UI will slowly push the user to do this in this point of view, java(script) evaluator introduce and validate the output using test cases in batches to achieve basic general algo first, then corner cases.
