### ISSUE TITLE
create Ui interface and modify UI-related classes' structure

### ISSUE THREAD

**Issue by nattanyz** [AY1920S1-CS2103-F09-2/main#137]
`Ui` interface will serve as API reference for `Gui`. all team members can refer to this, especially @PhireHandy in implementing `Responder` commands.

will modify UI-related classes to match MVC pattern more closely, or at least add a facade class to go between `Gui`'s rendering and logic it requires (interfacing with `FlashCard`s). @huiminlim any input/feedback, from architecture point of view? 

do we need a listener for checking when decks/cards are modified?

another question, @huiminlim : is it feasible to modify `Deck`s to use `ObservableList`s instead? this may be useful for GUI purposes. let me know if you have clarifications/comments.

**Comment by huiminlim** [comment]
@nattanyz is this a technical decision now by team that we are using facade and MVC and observable in Flash Card Pro?

**Comment by huiminlim** [comment]
> "will modify UI-related classes to match MVC pattern more closely, or at least add a facade class to go between Gui's rendering and logic it requires (interfacing with FlashCards). "

- Don't quite get what are you trying to say, can explain further what is the planned course of action, what to add?
- Is there any justification for the facade? There is nothing beyond flashcards via accessing i.e. gui->flashcard-> <ends here??>. Correct me if i am wrong.
- Plus, how does responses come in here. Isn't it acting sort of like a facade?

> do we need a listener for checking when decks/cards are modified?
`another` question, is it feasible to modify Decks to use ObservableLists instead? this may be useful for GUI purposes. let me know if you have clarifications/comments.

- Can define what object/(?) is "ObservableLists"? List of " FlashCardDisplay" objects?
- If i modify deck/card, and I also handle ObservableList (for what i interpret" FlashCardDisplay" object) in my deck/card, this means i update the " FlashCardDisplay" object  = "ObservableLists" in after I modify, if follow this? Then, no need listener as such.
