### ISSUE TITLE
Regex: Exit command

### ISSUE THREAD

**Issue by huiminlim** [AY1920S1-CS2103-F09-2/main#146]
@PhireHandy 

I printed out each input I have entered via this code insertion:
![image](https://user-images.githubusercontent.com/43434313/67595065-5a162080-f798-11e9-9b38-31919abc7602.png)

I tried to test `exit` but i did not receive the correct output.

![image](https://user-images.githubusercontent.com/43434313/67595031-47035080-f798-11e9-9b82-ca43f26fdbf4.png)

I suspect the problem is the dot after the `exit`, i.e. `(exit)**.**`

After removing the dot, we get this 
![image](https://user-images.githubusercontent.com/43434313/67595153-89c52880-f798-11e9-9ab9-8af1fa062d1e.png)

Let me know if this is a change I should make to test exit. thank you!

**Comment by AHaliq** [comment]
I should add takeInput should not throw Exceptions. There should also be no try catch around the for loop. All exceptions must be handled in lambdas.

**Comment by huiminlim** [comment]
Noted and removed the exceptions in takeInput. Waiting for gui to implement the exceptions.

@nattanyz fyi.

Thanks
