### ISSUE TITLE
When stats.json is deleted/not present, there is a "STATS JSON IS ILL FORMED" error message

### ISSUE THREAD

**Issue by nattanyz** [AY1920S1-CS2103-F09-2/main#283]
![image](https://user-images.githubusercontent.com/27663706/68269058-54bbae80-0093-11ea-9463-8b1757279022.png)

**Comment by nattanyz** [comment]
Also, there seems to be an extra space before "day" in the stats.json file. Not sure if this is to be expected?
![image](https://user-images.githubusercontent.com/27663706/68269132-8e8cb500-0093-11ea-86cd-b7c39813c096.png)

**Comment by AHaliq** [comment]
I've merged the fix, let me know if alls good.
