### ISSUE TITLE
Possible to "Start Review" when deck is empty

### ISSUE THREAD

**Issue by nattanyz** [AY1920S1-CS2103-F09-2/main#285]
![image](https://user-images.githubusercontent.com/27663706/68281781-55fcd380-00b3-11ea-9343-7b62d3793634.png)
![image](https://user-images.githubusercontent.com/27663706/68281807-6745e000-00b3-11ea-84aa-4e5f791dcb83.png)

Can't terminate the test by pressing "End Session", need to click on deckListView to exit.

**Comment by shawnpunchew11** [comment]
Solved by creating a popup window if the deck is empty
