### ISSUE TITLE
Development Environment Mac vs Windows 10

### ISSUE THREAD

**Issue by huiminlim** [AY1920S1-CS2103-F09-2/main#99]
I was running gradlew build and this test failed. I was wondering if it is a development environment issue.

![image](https://user-images.githubusercontent.com/43434313/67298322-aefa3280-f51d-11e9-81b4-8f3b72b68a87.png)

![image](https://user-images.githubusercontent.com/43434313/67298356-b9b4c780-f51d-11e9-8314-d8ade7965255.png)

Interestingly it did pass travis. So KIV here in case it might appear again.

**Comment by AHaliq** [comment]
are you using windows? the test uses `~` for the user's home directory. By default, java does not parse `~`. The test is showing that the function does. Travis runs a Linux machine to build.

**Comment by huiminlim** [comment]
yup using Windows 10. So is it normal for asset to fail?

**Comment by AHaliq** [comment]
yeah, an elegant fix will be to detect os and skip that test. Is it necessary?

**Comment by huiminlim** [comment]
If it interferes with saving json properly in Windows 10, it is a bug. Might need to devote time to testing to see if this thing happens again. Presume that this code is something you tried in iP and I managed to see a data file created in my PC when I tested, so should be fine for now.

**Comment by huiminlim** [comment]
Ok sure, that's great.

**Comment by AHaliq** [comment]
Out of curiosity can you run these two lines of code in main and see the output?
`FileReadWrite.resolve("~")`
and
`System.getProperty("user.home")`

**Comment by huiminlim** [comment]
![image](https://user-images.githubusercontent.com/43434313/67302271-401fd800-f523-11e9-92b0-539955d09dce.png)

FileReadWrite gives error, i amended to something else
![image](https://user-images.githubusercontent.com/43434313/67302429-73fafd80-f523-11e9-9e6a-c602903540e3.png)

**Comment by AHaliq** [comment]
what does the error for `FileReadWrite.resolve("~");` say?

**Comment by huiminlim** [comment]
Think you need two arg
![image](https://user-images.githubusercontent.com/43434313/67302815-0ac7ba00-f524-11e9-9ea7-1a9a189c5f0e.png)

**Comment by AHaliq** [comment]
oh my bad. `FileReadWrite.resolve("~",".\");`

**Comment by huiminlim** [comment]
![image](https://user-images.githubusercontent.com/43434313/67303170-a2c5a380-f524-11e9-83b1-d0f399805650.png)

Adding the escape char gets
![image](https://user-images.githubusercontent.com/43434313/67303253-c38df900-f524-11e9-9670-dd8f96dd669c.png)

**Comment by huiminlim** [comment]
This is the root specific to my pc

**Comment by AHaliq** [comment]
Hmm, so `~` seems to be working. I think its the `/` vs `\` issue again.

Maybe this test would work on your end:

`assertEquals(FileReadWrite.resolve(System.getProperty("user.home"), "./Desktop/b"), FileReadWrite.resolve("~/Desktop/a", "../b"));`

**Comment by huiminlim** [comment]
Yup it did, will leave there as commented code for those using gradlew to build. Will keep the original test for travis. Thank you!
